server:
  port: 8088
#首页配置
  servlet:
    context-path: /kou

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  thymeleaf:
    cache: false

  messages:
    basename: i18n.login

